name: Deploy to Dokploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Dokploy deploy
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            https://dokploy.n8nmayidevai.site/api/deploy/8JdLkuDzSjzLrxcL-CK2W
